spring.application.name=academic-service
jwt.secret=6L0a2EhqBv6hK8dY3nSxP5WvXJtR9GmQfNcZ1IuAe4U
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5433/acad_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
